Repository coreos/tectonic-installer, pull requests merged in 2018-03, with the labels that each got.

#3045 modules/container_linux: avoid shell
  modules/container_linux/main.tf
  modules/container_linux/outputs.tf
Labels: platform/aws, platform/bare-metal, run-smoke-tests

#3046 Rename config yaml keys camel case
  contrib/tectonic-cli-examples/config.yml
  examples/tectonic.aws.yaml
  installer/pkg/config-generator/fixtures/test-aws.yaml
  installer/pkg/config-generator/fixtures/test.yaml
  installer/pkg/config/aws/config.go
  installer/pkg/config/aws/types.go
  installer/pkg/config/azure/config.go
  installer/pkg/config/azure/types.go
  installer/pkg/config/gcp/config.go
  installer/pkg/config/gcp/types.go
  installer/pkg/config/govcloud/config.go
  installer/pkg/config/metal/config.go
  installer/pkg/config/metal/types.go
  installer/pkg/config/openstack/config.go
  installer/pkg/config/openstack/types.go
  installer/pkg/config/types.go
  installer/pkg/config/vmware/config.go
  installer/pkg/config/vmware/types.go
  tests/rspec/lib/config_file.rb
  tests/smoke/aws/vars/aws.basic.yaml
Labels: platform/aws, platform/bare-metal, run-smoke-tests

#3042 frontend: Change DEFAULT_CLUSTER_CONFIG to FIELD_DEFAULTS and make Field's default optional
  installer/frontend/__tests__/fields.js
  installer/frontend/actions.js
  installer/frontend/cluster-config.js
  installer/frontend/components/aws-cloud-credentials.jsx
  installer/frontend/components/aws-submit-keys.jsx
  installer/frontend/components/aws-tags.jsx
  installer/frontend/components/aws-vpc.jsx
  installer/frontend/components/bm-credentials.jsx
  installer/frontend/components/bm-hostname.jsx
  installer/frontend/components/bm-matchbox.jsx
  installer/frontend/components/bm-nodeforms.jsx
  installer/frontend/components/bm-sshkeys.jsx
  installer/frontend/components/certificate-authority.jsx
  installer/frontend/components/cluster-info.jsx
  installer/frontend/components/nodes.jsx
  installer/frontend/components/users.jsx
  installer/frontend/fields.js
  installer/frontend/form.js
  installer/frontend/reducer.js
Labels: run-gui-tests

#3038 frontend: Fix final Submit button to disable after being clicked
  installer/frontend/server.js
Labels: run-gui-tests

#3050 modules/tls: add uuid function to created certs
  modules/tls/etcd/signed/main.tf
  modules/tls/identity/self-signed/main.tf
  modules/tls/ingress/self-signed/main.tf
  modules/tls/kube/self-signed/aggregator_ca.tf
  modules/tls/kube/self-signed/ca.tf
Labels: platform/aws, run-smoke-tests

#3058 move ingress namespace to bootkube
  modules/bootkube-ut2/resources/manifests/02-ingress-namespace.yaml
  modules/bootkube/resources/manifests/02-ingress-namespace.yaml
  modules/tectonic/resources/tectonic.sh
Labels: platform/govcloud, run-smoke-tests

#3065 frontend: Remove unused `url` and `schema` validators
  installer/frontend/validate.js
Labels: run-gui-tests

#3063 tests: Adjust log archive step to new cli folder structure
  Jenkinsfile
Labels: platform/aws, platform/azure, run-smoke-tests

#3068 installer: Remove installer/Makefile
  installer/Makefile
Labels: platform/aws, platform/bare-metal, run-gui-tests, run-smoke-tests

#3053 Tnc bootstrap
  config.tf
  installer/pkg/workflow/install.go
  installer/pkg/workflow/utils.go
  modules/aws/master-asg/master.tf
  modules/aws/vpc/master-elb.tf
  modules/aws/vpc/outputs.tf
  modules/aws/vpc/sg-elb.tf
  modules/aws/vpc/sg-master.tf
  modules/aws/worker-asg/worker.tf
  modules/bootkube-ut2/assets.tf
  modules/bootkube-ut2/resources/manifests/ncg-config.yaml
  modules/bootkube-ut2/resources/manifests/ncg.yaml
  modules/bootkube-ut2/resources/manifests/tectonic-node-controller-config.yaml
  modules/bootkube-ut2/resources/manifests/tectonic-node-controller.yaml
  modules/bootkube-ut2/variables.tf
  steps/assets/ignition-ncg.tf
  steps/assets/resources/rm-assets.sh
  steps/assets/tectonic.tf
  steps/bootstrap/outputs.tf
  steps/bootstrap/s3-assets.tf
  steps/bootstrap/tnc-s3.tf
  steps/joining/inputs.tf
  steps/joining/ncg.tf
  steps/joining/tnc.tf
Labels: platform/aws, run-smoke-tests

#3081 installer,tests: standardize CLI flags
  README.md
  installer/cmd/tectonic/main.go
  tests/rspec/lib/aws_cluster.rb
Labels: platform/aws, run-smoke-tests

#3078 frontend: Fix AWS custom subnet validation bug when AWS region changes
  installer/frontend/aws-actions.js
  installer/frontend/ui-tests/output/aws-custom-vpc.tfvars
  installer/frontend/ui-tests/output/aws-external-etcd.tfvars
Labels: run-gui-tests

#3089 installer: For missing license / pull secret, log as INFO with filenames
  installer/api/handlers_tectonic.go
Labels: run-gui-tests

#3077 run TNC as a static pod before cluster having state
  modules/bootkube-ut2/assets.tf
  modules/bootkube-ut2/resources/bootkube.sh
  modules/bootkube-ut2/resources/manifests/tectonic-node-controller-config.yaml
  modules/bootkube-ut2/resources/manifests/tectonic-node-controller-pod.yaml
  modules/bootkube-ut2/resources/tnc-config
  modules/tectonic/resources/tectonic-wrapper.sh
  tests/smoke/cluster_test.go
Labels: platform/aws, run-smoke-tests

#3096 config.tf: Bump kvo to v1.7.14-kvo.1 and tectonic version to 1.7.14-tectonic.1
  config.tf
Labels: platform/aws, platform/azure, platform/bare-metal, run-smoke-tests

#3064 tests: Adjust log-analyzer-copy to missing build folder
  tests/jenkins-jobs/scripts/log-analyzer-copy.sh
Labels: platform/aws, platform/azure, run-smoke-tests

#3088 installer,tests: stub out node pools
  installer/BUILD.bazel
  installer/cmd/tectonic/BUILD.bazel
  installer/cmd/tectonic/main.go
  installer/pkg/config-generator/fixtures/test-aws.yaml
  installer/pkg/config-generator/fixtures/test.yaml
  installer/pkg/config-generator/generator.go
  installer/pkg/config-generator/generator_test.go
  installer/pkg/config/BUILD.bazel
  installer/pkg/config/parser.go
  installer/pkg/config/types.go
  installer/pkg/config/validate.go
  installer/pkg/config/validate_test.go
  installer/pkg/terraform-generator/tectonic.go
  installer/pkg/workflow/BUILD.bazel
  installer/pkg/workflow/fixtures/aws.basic.yaml
  installer/pkg/workflow/init_test.go
  installer/pkg/workflow/utils.go
  tests/rspec/lib/config_file.rb
  tests/smoke/aws/vars/aws.basic.yaml
Labels: platform/aws, run-smoke-tests

#3102 tests: update certificates for metal tests (#2885)
  tests/smoke/bare-metal/fake-creds/ca.crt
  tests/smoke/bare-metal/fake-creds/ca.key
  tests/smoke/bare-metal/fake-creds/client.crt
  tests/smoke/bare-metal/fake-creds/client.key
  tests/smoke/bare-metal/fake-creds/server.crt
  tests/smoke/bare-metal/fake-creds/server.key
  tests/smoke/bare-metal/vars/metal.tfvars.json
Labels: area/testing, platform/bare-metal, run-smoke-tests

#3097 config.tf: Bump kvo to v1.8.9-kvo.1, console to v5.0.4, tectonic to 1.8.9-tectonic.1
  config.tf
Labels: platform/aws, platform/azure, platform/bare-metal, run-smoke-tests

#3098 config.tf: Bump kvo to v1.8.4-kvo.8 which knows how to upgrade from the 1.7.14 release.
  config.tf
Labels: platform/aws, platform/azure, platform/bare-metal, run-smoke-tests

#3110 tests: disable console tests
  tests/rspec/lib/shared_examples/k8s.rb
Labels: area/testing, platform/aws, run-smoke-tests

#3093 tests: Print tf logs only on failure
  tests/rspec/lib/aws_cluster.rb
Labels: platform/aws, run-smoke-tests

#3095 installer: remove terraform-provider-matchbox
  bill-of-materials.json
  installer/glide.lock
  installer/glide.yaml
  installer/vendor/github.com/coreos/terraform-provider-matchbox/BUILD.bazel
  installer/vendor/github.com/coreos/terraform-provider-matchbox/LICENSE
  installer/vendor/github.com/coreos/terraform-provider-matchbox/NOTICE
  installer/vendor/github.com/coreos/terraform-provider-matchbox/main.go
  installer/vendor/github.com/coreos/terraform-provider-matchbox/matchbox/matchbox.go
  installer/vendor/github.com/coreos/terraform-provider-matchbox/matchbox/provider.go
  installer/vendor/github.com/coreos/terraform-provider-matchbox/matchbox/resource_group.go
  installer/vendor/github.com/coreos/terraform-provider-matchbox/matchbox/resource_profile.go
Labels: platform/aws, run-smoke-tests

#3111 tests: update certificates for metal tests (#2885) (#3102)
  tests/smoke/bare-metal/fake-creds/ca.crt
  tests/smoke/bare-metal/fake-creds/ca.key
  tests/smoke/bare-metal/fake-creds/client.crt
  tests/smoke/bare-metal/fake-creds/client.key
  tests/smoke/bare-metal/fake-creds/server.crt
  tests/smoke/bare-metal/fake-creds/server.key
  tests/smoke/bare-metal/vars/metal.tfvars.json
Labels: area/testing, platform/bare-metal, run-smoke-tests

#3103 config.tf: Bump hyperkube to v1.8.9_coreos.1 and kvo to v1.8.9-kvo.2.
  config.tf
Labels: platform/aws, platform/azure, platform/bare-metal, run-smoke-tests

#3104 config.tf: Bump hyperkube to v1.7.14_coreos.1, kvo to v1.7.14-kvo.2.
  config.tf
Labels: platform/aws, platform/azure, platform/bare-metal, run-smoke-tests

#3112 tests: Raise error on failed tectonic / terraform command
  tests/rspec/lib/aws_cluster.rb
  tests/rspec/lib/cluster.rb
Labels: platform/aws, platform/bare-metal, run-smoke-tests

#3092 modules/vpc: support re-apply of terraform when aws AZ number changes
  modules/aws/vpc/common.tf
  modules/aws/vpc/existing-vpc.tf
  modules/aws/vpc/variables.tf
  modules/aws/vpc/vpc-private.tf
  modules/aws/vpc/vpc-public.tf
  modules/aws/vpc/vpc.tf
  platforms/govcloud/main.tf
  platforms/govcloud/variables.tf
  steps/bootstrap/main.tf
  steps/variables.tf
Labels: platform/govcloud, run-smoke-tests

#3107 config.tf: Bump kvo to v1.8.4-kvo.9.
  config.tf
Labels: platform/aws, platform/azure, platform/bare-metal, run-smoke-tests

#3108 Fixes that were missed in #2972
  modules/bootkube-ut2/assets.tf
  modules/bootkube-ut2/resources/kubeconfig
  modules/bootkube-ut2/resources/kubeconfig-kubelet
  modules/tls/ca/self-signed/main.tf
  modules/tls/ca/user-provided/assets.tf
  modules/tls/ca/user-provided/outputs.tf
  modules/tls/ca/user-provided/variables.tf
Labels: platform/govcloud, run-smoke-tests

#3054 Cluster id fix
  installer/pkg/config-generator/generator.go
  installer/pkg/config-generator/generator_test.go
  installer/pkg/config/cluster.go
  installer/pkg/config/parser.go
  installer/pkg/config/types.go
  installer/pkg/workflow/BUILD.bazel
  installer/pkg/workflow/init.go
  installer/pkg/workflow/init_test.go
  installer/pkg/workflow/utils.go
  modules/bootkube-ut2/resources/manifests/cluster-config.yaml
  steps/assets/outputs.tf
  steps/bootstrap/inputs.tf
  steps/bootstrap/main.tf
  steps/bootstrap/outputs.tf
  steps/bootstrap/s3-assets.tf
  steps/bootstrap/tnc-s3.tf
  steps/joining/inputs.tf
  steps/joining/masters.tf
  steps/joining/workers.tf
  steps/variables.tf
Labels: platform/aws, run-smoke-tests

#3074 tests: add master and worker role
  Jenkinsfile
  tests/smoke/aws/vars/aws-basic.yaml
Labels: platform/aws, run-smoke-tests

#3126 cli: change default log level to info
  installer/cmd/tectonic/main.go
Labels: platform/aws, run-smoke-tests

#3127 tnc-config: Fix typo in the config.
  modules/bootkube-ut2/resources/tnc-config
Labels: platform/aws, run-smoke-tests

#3131 Cli: get terraform binary from inside the package
  installer/pkg/workflow/BUILD.bazel
  installer/pkg/workflow/executor.go
  installer/pkg/workflow/terraform.go
  tests/rspec/spec/spec_helper.rb
Labels: platform/aws, run-smoke-tests

#3135 Remove multiple clusters from config
  examples/tectonic.aws.yaml
  installer/pkg/config-generator/fixtures/test-aws.yaml
  installer/pkg/config-generator/fixtures/test.yaml
  installer/pkg/config-generator/generator_test.go
  installer/pkg/config/BUILD.bazel
  installer/pkg/config/cluster.go
  installer/pkg/config/config.go
  installer/pkg/config/parser.go
  installer/pkg/config/types.go
  installer/pkg/workflow/convert.go
  installer/pkg/workflow/fixtures/aws.basic.yaml
  installer/pkg/workflow/init.go
  installer/pkg/workflow/init_test.go
  installer/pkg/workflow/utils.go
  tests/rspec/lib/config_file.rb
  tests/smoke/aws/vars/aws-basic.yaml
  tests/smoke/aws/vars/aws-ca.yaml
  tests/smoke/aws/vars/aws-exp.yaml
  tests/smoke/aws/vars/aws-net-flannel.yaml
  tests/smoke/aws/vars/aws-vpc-internal.yaml
Labels: platform/aws, run-smoke-tests

#3079 Etcd tnc
  config.tf
  installer/pkg/workflow/destroy.go
  installer/pkg/workflow/install.go
  installer/pkg/workflow/utils.go
  modules/aws/etcd/ignition.tf
  modules/aws/etcd/nodes.tf
  modules/bootkube/assets.tf
  modules/bootkube/resources/tnc-config
  modules/bootkube/variables.tf
  modules/dns/route53/etcd.tf
  modules/dns/route53/outputs.tf
  modules/dns/route53/variables.tf
  steps/assets/ignition-etcd.tf
  steps/assets/tectonic.tf
  steps/bootstrap/inputs.tf
  steps/bootstrap/main.tf
  steps/bootstrap/outputs.tf
  steps/bootstrap/s3-assets.tf
  steps/etcd/config.tf
  steps/etcd/etcd.tf
  steps/etcd/inputs.tf
  steps/etcd/tnc.tf
  steps/etcd/variables.tf
  steps/joining/inputs.tf
Labels: platform/aws, run-smoke-tests
