Repository coreos/tectonic-installer, pull requests merged in 2018-04, with the labels that each got.

#3151 config.tf: Bump tnc version, also update the ignitoin endpoint URL.
  config.tf
  installer/pkg/config-generator/ignition.go
  modules/aws/etcd/ignition.tf
  modules/bootkube/resources/manifests/tectonic-node-controller.yaml
  steps/bootstrap/s3-assets.tf
Labels: platform/aws, run-smoke-tests

#3152 Moved update-payload module to tectonic-release-automation repo
  .gitignore
  BUILD.bazel
  modules/update-payload/assets.tf
  modules/update-payload/config.tf
Labels: run-smoke-tests

#3158 Bump kube conformance
  Jenkinsfile
Labels: run-conformance-tests

#3159 modules: force etcd TLS client auth
  contrib/internal-cluster/vpn.tf
  modules/ignition/etcd.tf
Labels: platform/aws, run-smoke-tests

#3160 modules: force etcd TLS client auth
  contrib/internal-cluster/vpn.tf
  modules/ignition/etcd.tf
Labels: platform/aws, run-smoke-tests

#3150 Bump hyperkube to 1.9.6_coreos.0
  config.tf
Labels: platform/aws, platform/azure, platform/bare-metal, run-gui-tests, run-smoke-tests

#3166 Bumped Tectonic version
  config.tf
Labels: run-conformance-tests, run-gui-tests, run-smoke-tests

#3163 config.tf: bump default channel to 1.9-production
  Documentation/variables/config.md
  config.tf
Labels: platform/aws, run-smoke-tests

#3141 tests: add parameter to -v and update jenkinsfile
  images/kubernetes-e2e/Dockerfile
Labels: area/ci, area/testing, platform/aws, run-conformance-tests, run-smoke-tests

#3169 Fix cluster name when testing in Branches
  tests/rspec/lib/name_generator.rb
Labels: area/ci, area/testing, platform/aws, run-smoke-tests

#3164 cli: plumb-through per-platform steps
  installer/pkg/config/cluster.go
  installer/pkg/workflow/destroy.go
  installer/pkg/workflow/fixtures/terraform.tfvars
  installer/pkg/workflow/install.go
  installer/pkg/workflow/utils.go
Labels: platform/aws, run-smoke-tests

#3180 Bump track-1 K8s conformance tests to 1.9.6
  Jenkinsfile
  images/kubernetes-e2e/Dockerfile
  images/kubernetes-e2e/build.sh
Labels: run-conformance-tests, run-gui-tests, run-smoke-tests

#3148 module/bootkube: update k8s addons
  config.tf
  modules/bootkube/resources/manifests/kube-dns.yaml
  modules/bootkube/resources/manifests/kube-proxy.yaml
Labels: platform/aws, run-smoke-tests

#3178 module/bootkube: update k8s addons
  config.tf
  modules/bootkube/resources/manifests/kube-dns.yaml
  modules/bootkube/resources/manifests/kube-proxy.yaml
Labels: platform/aws, run-smoke-tests

#3186 remove tectonic_dns_name input variable
  installer/pkg/config/cluster.go
  modules/aws/vpc/master-elb.tf
  modules/aws/vpc/variables.tf
  modules/dns/powerdns/outputs.tf
  modules/dns/powerdns/records.tf
  modules/dns/powerdns/variables.tf
  modules/dns/route53/tectonic.tf
  modules/dns/route53/variables.tf
  steps/topology/main.tf
  steps/variables.tf
Labels: platform/aws, run-smoke-tests

#3189 add yaml2json support for admin vars
  installer/pkg/config-generator/BUILD.bazel
  installer/pkg/config/BUILD.bazel
  installer/pkg/config/types.go
  installer/pkg/validate/BUILD.bazel
  installer/pkg/workflow/BUILD.bazel
  installer/pkg/workflow/fixtures/aws.basic.yaml
  installer/pkg/workflow/fixtures/terraform.tfvars
Labels: platform/aws, run-smoke-tests

#3185 Bump Tectonic Console to v6.0.1.
  config.tf
Labels: platform/aws, run-conformance-tests, run-gui-tests, run-smoke-tests

#3183 Install assets only via Ignition
  installer/pkg/workflow/install.go
  installer/pkg/workflow/utils.go
  modules/bootkube/assets.tf
  modules/bootkube/manifests.tf
  modules/bootkube/outputs.tf
  modules/bootkube/service-account.tf
  modules/ignition/assets.tf
  modules/ignition/outputs.tf
  modules/ignition/resources/bin/gcs-puller.sh
  modules/ignition/resources/bin/s3-puller.sh
  modules/ignition/resources/paths/rm-assets.path
  modules/ignition/resources/services/init-assets.service
  modules/ignition/resources/services/k8s-node-bootstrap.service
  modules/ignition/resources/services/kubelet.service
  modules/ignition/resources/services/rm-assets.service
  modules/ignition/variables.tf
  modules/tectonic/assets.tf
  modules/tectonic/manifests.tf
  modules/tectonic/output.tf
  modules/tls/ca/self-signed/assets.tf
  modules/tls/ca/self-signed/outputs.tf
  modules/tls/etcd/assets.tf
  modules/tls/etcd/outputs.tf
  modules/tls/kube/assets.tf
  modules/tls/kube/outputs.tf
  steps/assets/ignition-bootstrap.tf
  steps/assets/local-files.tf
  steps/assets/resources/init-assets.sh
  steps/assets/resources/rm-assets.sh
  steps/topology/main.tf
  steps/topology/s3-assets.tf
  tests/rspec/lib/aws_cluster.rb
Labels: platform/aws, run-smoke-tests

#3142 Simplified Bazel build
  .bazelrc
  BUILD.bazel
  Jenkinsfile
  README.md
  WORKSPACE
  examples/BUILD.bazel
  images/tectonic-installer/Dockerfile
  installer/BUILD.bazel
  installer/cmd/tectonic/BUILD.bazel
  installer/pkg/workflow/utils.go
  tests/rspec/lib/aws_cluster.rb
  tests/rspec/lib/cluster.rb
  tests/rspec/lib/grafiti.rb
  tests/rspec/lib/shared_examples/build_folder_setup.rb
  tests/rspec/lib/tfstate_file.rb
  tests/rspec/spec/spec_helper.rb
  version.bzl
Labels: platform/aws, run-smoke-tests

#3196 Drop dex
  config.tf
  installer/pkg/config-generator/generator.go
  modules/tectonic/manifests.tf
  modules/tectonic/resources/manifests/rbac/binding-admin.yaml
  modules/tectonic/resources/manifests/secrets/identity-grpc-client.yaml
  modules/tectonic/resources/manifests/secrets/identity-grpc-server.yaml
  modules/tectonic/resources/manifests/updater/app_versions/app-version-tectonic-cluo.yaml
  modules/tectonic/resources/manifests/updater/app_versions/app-version-tectonic-monitoring.yaml
  modules/tectonic/resources/manifests/updater/operators/tectonic-cluo-operator.yaml
  modules/tectonic/resources/manifests/updater/operators/tectonic-prometheus-operator.yaml
  modules/tectonic/resources/manifests/updater/tectonic-monitoring-config.yaml
  modules/tectonic/resources/tectonic.sh
  modules/tectonic/variables.tf
  modules/tls/identity/main.tf
  modules/tls/identity/outputs.tf
  modules/tls/identity/variables.tf
  steps/assets/tectonic.tf
  steps/assets/tls.tf
Labels: platform/aws, run-smoke-tests

#3199 config.tf: 1.8.9-tectonic.3, bump tco, kvo, console and tcluo
  config.tf
Labels: platform/aws, platform/azure, platform/govcloud, run-smoke-tests

#3195 config.tf: Bump kvo, tco, tcluo for 1.9.6
  config.tf
Labels: platform/azure, run-smoke-tests

#3203 Add registry
  .gitignore
  config.tf
  installer/glide.lock
  installer/glide.yaml
  installer/pkg/config-generator/BUILD.bazel
  installer/pkg/config-generator/generator.go
  installer/vendor/github.com/Sirupsen/logrus/BUILD.bazel
  installer/vendor/github.com/coreos/tectonic-config/config/kube-addon/config.go
  installer/vendor/github.com/coreos/tectonic-config/config/tectonic-utility/config.go
  installer/vendor/golang.org/x/crypto/bcrypt/BUILD.bazel
  installer/vendor/golang.org/x/crypto/bcrypt/base64.go
  installer/vendor/golang.org/x/crypto/bcrypt/bcrypt.go
  installer/vendor/golang.org/x/crypto/blowfish/BUILD.bazel
  installer/vendor/golang.org/x/crypto/blowfish/block.go
  installer/vendor/golang.org/x/crypto/blowfish/cipher.go
  installer/vendor/golang.org/x/crypto/blowfish/const.go
  installer/vendor/golang.org/x/crypto/ssh/terminal/BUILD.bazel
  modules/ignition/resources/services/kubelet.service
  steps/assets/ignition-bootstrap.tf
Labels: platform/aws, run-smoke-tests

#3194 Bump Tectonic Console to v6.0.4.
  config.tf
Labels: platform/aws, run-gui-tests, run-smoke-tests

#3208 config.tf: Bump kvo to v1.9.6-kvo.3, tco to 0.6.4, tcluo to v0.3.2
  config.tf
Labels: run-gui-tests, run-smoke-tests

#3207 Bump Tectonic Console to v6.0.5 for 1.9.6.
  config.tf
Labels: platform/aws, run-conformance-tests, run-gui-tests, run-smoke-tests

#3209 Bump KVO to 196-4 to support Console 6.0.5
  config.tf
Labels: run-gui-tests, run-smoke-tests

#3206 bump tnco,tuo;
  config.tf
  modules/tectonic/manifests.tf
  modules/tectonic/resources/manifests/updater/app_versions/app-version-tectonic-cluo.yaml
  modules/tectonic/resources/manifests/updater/operators/tectonic-cluo-operator.yaml
  modules/tectonic/resources/tectonic.sh
  tests/rspec/lib/operators.rb
Labels: platform/aws, run-smoke-tests

#3204 Fix paths in .bazelrc for Bazel >0.12.x
  .bazelrc
Labels: platform/aws, run-smoke-tests

#3205 config.tf: Change kube-addon-operator repo.
  config.tf
  modules/tectonic/manifests.tf
  modules/tectonic/resources/manifests/updater/app_versions/app-version-kube-addon.yaml
  modules/tectonic/resources/manifests/updater/operators/kube-addon-operator.yaml
  modules/tectonic/resources/tectonic.sh
  tests/rspec/lib/operators.rb
Labels: platform/aws, run-smoke-tests

#3133 tests: save terraform logs when timeout
  tests/rspec/lib/aws_cluster.rb
Labels: area/ci, area/testing, platform/aws, run-smoke-tests

#3211 steps: bootstrap cleanup
  installer/pkg/workflow/utils.go
  modules/ignition/resources/services/rm-assets.service
  steps/assets/resources/rm-assets.sh
  tests/rspec/lib/cluster.rb
Labels: platform/aws, run-smoke-tests

#3215 config.tf: Bump operators to beryllium-m2 release
  config.tf
Labels: platform/aws, run-smoke-tests
