Repository coreos/tectonic-installer, pull requests merged in 2018-05, with the labels that each got.

#3219 installer: Fix the plural definition of the aws struct.
  installer/pkg/config/aws/aws.go
Labels: platform/aws, run-smoke-tests

#3224 modules: eliminate bootstrap cleanup race
  modules/ignition/resources/services/rm-assets.service
Labels: platform/aws, run-smoke-tests

#3222 config.tf: Bump tco.
  config.tf
Labels: platform/aws, run-smoke-tests

#3212 bump alm to 0.4.0
  config.tf
Labels: platform/aws, run-smoke-tests

#3218 clean up obsolete config
  config.tf
  installer/pkg/config/cluster.go
  installer/pkg/config/types.go
  modules/ignition/assets.tf
  modules/ignition/etcd.tf
  modules/ignition/outputs.tf
  modules/ignition/resources/dropins/40-etcd-cluster.conf
  modules/ignition/resources/proxy/10-default-env.conf
  modules/ignition/resources/proxy/profile.env
  modules/ignition/resources/services/tx-off.service
  modules/ignition/resources/sysctl.d/max-user-watches.conf
  modules/ignition/resources/udev/66-azure-storage.rules
  modules/ignition/variables.tf
  steps/assets/aws/main.tf
  steps/assets/base/ignition-bootstrap.tf
  steps/assets/libvirt/main.tf
Labels: platform/aws, run-smoke-tests

#3225 tectonic-alm-operator: update deployment for newer x-operator base image
  modules/tectonic/resources/manifests/updater/operators/tectonic-alm-operator.yaml
Labels: platform/aws, run-conformance-tests, run-smoke-tests

#3193 Scale test
  installer/pkg/workflow/destroy.go
  installer/pkg/workflow/init.go
  installer/pkg/workflow/init_test.go
  installer/pkg/workflow/install.go
  installer/pkg/workflow/utils.go
  steps/bootstrap/aws/outputs.tf
  steps/joining_masters/config.tf
  steps/joining_masters/inputs.tf
  steps/joining_masters/masters.tf
  steps/joining_masters/variables-aws.tf
  steps/masters/aws/config.tf
  steps/masters/aws/inputs.tf
  steps/masters/aws/main.tf
  steps/masters/aws/masters.variables.tf
  steps/masters/aws/variables-aws.tf
  steps/masters/libvirt/config.tf
  steps/masters/libvirt/inputs.tf
  steps/masters/libvirt/main.tf
  steps/masters/libvirt/variables-libvirt.tf
  tests/rspec/lib/aws_cluster.rb
  tests/rspec/lib/cluster.rb
  tests/rspec/lib/shared_examples/k8s.rb
Labels: platform/aws, run-smoke-tests

#3229 tectonic-alm-operator: Use command instead of args.
  modules/tectonic/resources/manifests/updater/operators/tectonic-alm-operator.yaml
Labels: platform/azure, run-smoke-tests

#3201 fix: Loosen Tectonic's Azure Resource Group capture
  modules/azure/vnet/variables.tf
  modules/dns/azure/variables.tf
Labels: platform/azure, run-smoke-tests

#3114 config.tf: bump tls provider to fix CA
  config.tf
Labels: platform/aws, run-smoke-tests

#3233 installer: allow empty cidr to take default
  config.tf
  installer/pkg/config/BUILD.bazel
  installer/pkg/config/cluster.go
  installer/pkg/config/parser.go
  installer/pkg/config/validate.go
  installer/pkg/validate/validate.go
  installer/pkg/validate/validate_test.go
  steps/assets/aws/main.tf
  steps/assets/libvirt/main.tf
  tests/smoke/aws/vars/aws-basic.tfvars.json
  tests/smoke/aws/vars/aws-basic.yaml
Labels: platform/aws, run-smoke-tests

#3239 images: Pin bazel to specific version in docker image
  Jenkinsfile
  images/tectonic-builder/Dockerfile
  images/tectonic-builder/Dockerfile.bazel
Labels: platform/aws, run-smoke-tests

#3240 Remove public resources in private VPC deployment
  installer/pkg/config/aws/aws.go
Labels: platform/aws, run-smoke-tests

#3236 installer/pkg/config: validate cluster name
  installer/pkg/config/BUILD.bazel
  installer/pkg/config/validate.go
  installer/pkg/workflow/BUILD.bazel
  installer/pkg/workflow/init.go
  installer/pkg/workflow/utils.go
Labels: platform/aws, run-smoke-tests

#3241 Gazelle cmd
  BUILD.bazel
  installer/BUILD.bazel
  installer/cmd/tectonic/BUILD.bazel
Labels: platform/aws, run-smoke-tests

#3242 Bazel output
  .bazelrc
  .gitignore
Labels: platform/aws, run-smoke-tests

#3245 Jenkinsfile: remove wrapper around slackSend
  Jenkinsfile
Labels: area/ci, platform/aws, run-smoke-tests

#3252 *: remove unused s3 bucket name option
  Documentation/variables/aws.md
  installer/pkg/config/aws/aws.go
  steps/variables-aws.tf
Labels: platform/aws, run-smoke-tests

#3251 *: remove ddns options
  Documentation/variables/config.md
  config.tf
  examples/tectonic.aws.yaml
  examples/tectonic.libvirt.yaml
  installer/pkg/config/cluster.go
  installer/pkg/config/types.go
  modules/dns/ddns/README.md
  modules/dns/ddns/main.tf
  modules/dns/ddns/variables.tf
Labels: platform/aws, run-smoke-tests

#3244 Readme deps
  BUILD.bazel
  Jenkinsfile
  README.md
  installer/README.md
Labels: platform/aws, run-smoke-tests

#3254 inst-1093: fix rm-assets race conditions
  modules/ignition/resources/services/rm-assets.service
Labels: platform/aws, run-smoke-tests
