Repository coreos/tectonic-installer, pull requests merged in 2018-02, with the labels that each got.

#2929 bumped kvo version
  config.tf
Labels: platform/aws, run-smoke-tests

#2932 kvo + console bump
  config.tf
Labels: run-gui-tests, run-smoke-tests

#2933 tests/frontend: Fix GUI tfvars test to wait until diff is complete
  installer/frontend/ui-tests/utils/terraformTfvars.js
Labels: run-gui-tests

#2934 tests/frontend: Add "id" attributes to simplify Nightwatch tests
  installer/frontend/components/submit-definition.jsx
  installer/frontend/components/ui.jsx
  installer/frontend/ui-tests/pages/defineMastersPage.js
  installer/frontend/ui-tests/pages/defineWorkersPage.js
  installer/frontend/ui-tests/pages/downloadAssetsPage.js
  installer/frontend/ui-tests/pages/networkingPage.js
  installer/frontend/ui-tests/pages/submitPage.js
  installer/frontend/ui-tests/utils/terraformTfvars.js
Labels: run-gui-tests

#2927 installer: support declarative x-compile
  BUILD.bazel
  Documentation/dev/build.md
  installer/vendor/github.com/Sirupsen/logrus/BUILD.bazel
  installer/vendor/github.com/kardianos/osext/BUILD.bazel
  installer/vendor/github.com/mattn/go-isatty/BUILD.bazel
  installer/vendor/github.com/shirou/gopsutil/cpu/BUILD.bazel
  installer/vendor/github.com/shirou/gopsutil/host/BUILD.bazel
  installer/vendor/github.com/shirou/gopsutil/internal/common/BUILD.bazel
  installer/vendor/github.com/shirou/gopsutil/mem/BUILD.bazel
  installer/vendor/github.com/shirou/gopsutil/net/BUILD.bazel
  installer/vendor/github.com/shirou/gopsutil/process/BUILD.bazel
  installer/vendor/golang.org/x/crypto/ssh/terminal/BUILD.bazel
  tarball
Labels: platform/aws, run-smoke-tests

#2915 Installer API: Add buildTime and tectonicVersion
  .bazelrc
  buildvars.sh
  installer/api/BUILD.bazel
  installer/api/api.go
  installer/api/handlers_latest_release.go
  installer/version/BUILD.bazel
  installer/version/version.go
Labels: run-gui-tests, tectonic/frontend

#2930 config.tf: Update tectonic-error-server to 1.1
  config.tf
Labels: platform/aws, run-smoke-tests

#2921 bootkube: Add ingress namespace creation.
  modules/bootkube/resources/manifests/02-ingress-namespace.yaml
Labels: platform/azure, platform/govcloud, run-smoke-tests

#2938 buildvars: BUILD_TIME in ISO 8601 format
  buildvars.sh
Labels: run-gui-tests, tectonic/frontend

#2950 Upgrade fix for CA certs
  modules/tectonic/resources/manifests/console/deployment.yaml
  modules/tectonic/resources/manifests/updater/operators/tectonic-channel-operator.yaml
Labels: platform/aws, run-smoke-tests

#2368 Azure: add German locations to fault domain map
  platforms/azure/variables.tf
Labels: platform/azure, run-smoke-tests

#2948 digitalocean: Add support for DigitalOcean
  .editorconfig
  Documentation/dev/digitalocean/README.md
  Documentation/dev/node-bootstrap-flow.md
  bazel-bin
  bazel-genfiles
  bazel-out
  bazel-tectonic-installer
  bazel-testlogs
  examples/terraform.tfvars.digitalocean
  modules/digitalocean/etcd/dns.tf
  modules/digitalocean/etcd/ignition.tf
  modules/digitalocean/etcd/nodes.tf
  modules/digitalocean/etcd/outputs.tf
  modules/digitalocean/etcd/variables.tf
  modules/digitalocean/master/ignition.tf
  modules/digitalocean/master/loadbalancer.tf
  modules/digitalocean/master/master.tf
  modules/digitalocean/master/outputs.tf
  modules/digitalocean/master/resources/init-assets.sh
  modules/digitalocean/master/resources/register-master.sh
  modules/digitalocean/master/resources/rm-assets.sh
  modules/digitalocean/master/variables-ignition.tf
  modules/digitalocean/master/variables.tf
  modules/digitalocean/worker/ignition.tf
  modules/digitalocean/worker/variables-ignition.tf
  modules/digitalocean/worker/variables.tf
  modules/digitalocean/worker/worker.tf
  platforms/digitalocean/assets.tf
  platforms/digitalocean/config.tf
  platforms/digitalocean/main.tf
  platforms/digitalocean/resources/do-puller.sh
  platforms/digitalocean/resources/do-pusher.sh
  platforms/digitalocean/resources/etc/resolved.conf
  platforms/digitalocean/spaces.tf
  platforms/digitalocean/tectonic.tf
  platforms/digitalocean/tls.tf
  platforms/digitalocean/variables.tf
Labels: platform/govcloud, run-smoke-tests

#2914 frontend: Add additional info for AWS VPCs and subnets
  installer/api/handlers_aws.go
  installer/assets/frontend/css/styles.css
  installer/frontend/components/aws-cloud-credentials.jsx
  installer/frontend/components/aws-vpc.jsx
  installer/frontend/components/cidr.jsx
  installer/frontend/components/ui.jsx
  installer/pkg/aws/getters.go
Labels: run-gui-tests

#2951 frontend & tests: Disable metal GUI option
  Jenkinsfile
  installer/cmd/installer/platforms.go
  installer/frontend/ui-tests/pages/platformPage.js
Labels: run-gui-tests

#2947 Installer: Move tectonicVersion and buildTime to /tectonic/facts
  installer/api/api.go
  installer/api/handlers_latest_release.go
  installer/api/handlers_tectonic.go
Labels: run-gui-tests, tectonic/frontend

#2954 modules/tectonic: fix alertmanager ingress config.
  config.tf
  modules/tectonic/resources/manifests/updater/tectonic-monitoring-config.yaml
Labels: platform/aws, platform/azure, release-blocker, run-smoke-tests

#2944 azure: Allow configurable root volume disk sizes
  Documentation/variables/azure.md
  examples/terraform.tfvars.azure
  modules/azure/etcd/etcd.tf
  modules/azure/etcd/variables.tf
  modules/azure/master-as/master.tf
  modules/azure/master-as/variables.tf
  modules/azure/worker-as/variables.tf
  modules/azure/worker-as/workers.tf
  platforms/azure/main.tf
  platforms/azure/variables.tf
Labels: platform/azure, run-smoke-tests

#2959 [Li] azure: Allow configurable root volume disk sizes
  Documentation/variables/azure.md
  examples/terraform.tfvars.azure
  modules/azure/etcd/etcd.tf
  modules/azure/etcd/variables.tf
  modules/azure/master-as/master.tf
  modules/azure/master-as/variables.tf
  modules/azure/worker-as/variables.tf
  modules/azure/worker-as/workers.tf
  platforms/azure/main.tf
  platforms/azure/variables.tf
Labels: platform/azure, run-smoke-tests

#2961 frontend: Use monospace font for Terraform log output
  installer/assets/frontend/css/styles.css
Labels: run-gui-tests

#2962 frontend: Add progress bar for Terraform destroy actions
  installer/frontend/components/tf-poweron.jsx
Labels: run-gui-tests

#2964 frontend: Fix state restore console.debug statement
  installer/frontend/app.jsx
Labels: run-gui-tests

#2907 tests: Run rspec tests out of bazel build output
  Jenkinsfile
  tests/rspec/lib/aws_vpc.rb
  tests/rspec/lib/azure_vpn.rb
  tests/rspec/lib/cluster.rb
  tests/rspec/lib/cluster_support.rb
  tests/rspec/lib/govcloud_vpc.rb
  tests/rspec/lib/metal_support.rb
  tests/rspec/lib/shared_examples/build_folder_setup.rb
  tests/rspec/lib/shared_examples/k8s.rb
  tests/rspec/lib/shared_examples/tls_setup.rb
  tests/rspec/lib/smoke_test.rb
  tests/rspec/spec/aws/basic_spec.rb
  tests/rspec/spec/aws/ca_spec.rb
  tests/rspec/spec/aws/custom_tls_spec.rb
  tests/rspec/spec/aws/exp_spec.rb
  tests/rspec/spec/aws/network_flannel_spec.rb
  tests/rspec/spec/aws/vpc_internal_spec.rb
  tests/rspec/spec/azure/basic_spec.rb
  tests/rspec/spec/azure/custom_tls_spec.rb
  tests/rspec/spec/azure/dns_spec.rb
  tests/rspec/spec/azure/example_spec.rb
  tests/rspec/spec/azure/external_self_hosted_etcd_spec.rb
  tests/rspec/spec/azure/external_spec.rb
  tests/rspec/spec/azure/private_external_spec.rb
  tests/rspec/spec/azure/self_hosted_etcd_spec.rb
  tests/rspec/spec/existing_cluster_spec.rb
  tests/rspec/spec/gcp/basic_spec.rb
  tests/rspec/spec/gcp/custom_tls_spec.rb
  tests/rspec/spec/gcp/ha_spec.rb
  tests/rspec/spec/govcloud/vpc_internal_spec.rb
  tests/rspec/spec/metal/basic_spec.rb
  tests/rspec/spec/metal/custom_tls_spec.rb
  tests/rspec/spec/spec_helper.rb
Labels: platform/azure, run-smoke-tests

#2963 kvo + console bump
  config.tf
Labels: platform/aws, platform/azure, platform/bare-metal, platform/govcloud, run-smoke-tests

#2956 Bump ALM to 0.3.1
  config.tf
  modules/tectonic/resources/manifests/updater/operators/tectonic-alm-operator.yaml
Labels: platform/aws, run-smoke-tests

#2966 Fix symlink from ignition vars to govcloud module
  modules/govcloud/master-asg/variables-ignition.tf
  modules/govcloud/master-asg/variables.tf
  modules/govcloud/worker-asg/variables-ignition.tf
  modules/govcloud/worker-asg/variables.tf
Labels: platform/govcloud, run-smoke-tests

#2935 frontend: Fix AWS regions duplicated error and add loading indicator
  installer/frontend/components/aws-cloud-credentials.jsx
Labels: run-gui-tests

#2943 frontend: Add React Error Boundaries to handle errors more gracefully
  installer/frontend/components/base.jsx
  installer/frontend/components/ui.jsx
Labels: run-gui-tests

#2942 frontend: Add loading indicator for AWS VPC subnets and clean up
  installer/frontend/components/aws-vpc.jsx
Labels: run-gui-tests

#2952 tests/frontend: Test that platform select has expected default value
  installer/frontend/ui-tests/pages/platformPage.js
Labels: run-gui-tests

#2955 tests: Add delay to ssh and update cl channel to beta
  tests/rspec/lib/cluster.rb
  tests/smoke/aws/vars/aws-ca.tfvars.json
  tests/smoke/aws/vars/aws-exp.tfvars.json
  tests/smoke/aws/vars/aws-net-flannel.tfvars.json
  tests/smoke/aws/vars/aws-vpc-internal.tfvars.json
  tests/smoke/azure/vars/basic.tfvars
  tests/smoke/azure/vars/dns.tfvars
  tests/smoke/azure/vars/example.tfvars
  tests/smoke/azure/vars/external.tfvars
  tests/smoke/azure/vars/private-cluster.tfvars
  tests/smoke/govcloud/vars/govcloud-vpc-internal.tfvars.json
Labels: area/testing, platform/aws, platform/azure, run-smoke-tests

#2846 azure: add option to enable boot diagnostics for VMs in azure
  Documentation/variables/config.md
  config.tf
  examples/terraform.tfvars.aws
  examples/terraform.tfvars.azure
  examples/terraform.tfvars.gcp
  examples/terraform.tfvars.govcloud
  examples/terraform.tfvars.metal
  examples/terraform.tfvars.openstack-neutron
  examples/terraform.tfvars.vmware
  modules/azure/etcd/etcd.tf
  modules/azure/etcd/variables.tf
  modules/azure/master-as/master.tf
  modules/azure/master-as/variables.tf
  modules/azure/resource-group/outputs.tf
  modules/azure/resource-group/resource-group.tf
  modules/azure/resource-group/variables.tf
  modules/azure/worker-as/variables.tf
  modules/azure/worker-as/workers.tf
  platforms/azure/main.tf
  tests/rspec/lib/azure_vpn.rb
  tests/smoke/azure/vars/basic.tfvars
  tests/smoke/azure/vars/dns.tfvars
  tests/smoke/azure/vars/example.tfvars
  tests/smoke/azure/vars/external.tfvars
  tests/smoke/azure/vars/private-cluster.tfvars
Labels: platform/azure, run-smoke-tests

#2980 tests/bazel/frontend: using bazel test to run GUI tests
  Jenkinsfile
  images/tectonic-builder/Dockerfile.bazel
  installer/BUILD.bazel
  installer/frontend/BUILD.bazel
  tests/smoke/BUILD.bazel
Labels: area/ci, area/testing, platform/aws, run-gui-tests, run-smoke-tests

#2990 installer: ensure reproducible build of bindata
  installer/assets/BUILD.bazel
Labels: run-gui-tests

#2979 frontend: Add message when in progress install is detected
  installer/frontend/components/tf-poweron.jsx
Labels: run-gui-tests

#2740 tests: all pods should be in running and none in crashloopbackoff
  tests/smoke/cluster_test.go
Labels: area/testing, do-not-merge, platform/aws, run-smoke-tests

#2988 tests: collect boot logs from azure
  Jenkinsfile
  tests/rspec/Gemfile
  tests/rspec/Gemfile.lock
  tests/rspec/lib/aws_support.rb
  tests/rspec/lib/azure_cluster.rb
  tests/rspec/lib/azure_support.rb
  tests/rspec/lib/cluster.rb
Labels: area/ci, area/testing, platform/azure, run-smoke-tests

#2997 monitoring: Fix migration and insecure image org
  config.tf
Labels: platform/aws, run-smoke-tests

#3000 frontend: Remove inFly updates from validate()
  installer/frontend/components/aws-vpc.jsx
  installer/frontend/form.js
Labels: run-gui-tests

#2996 frontend: Add AWS Paris (eu-west-3) region option
  installer/frontend/components/aws-cloud-credentials.jsx
Labels: run-gui-tests

#2977 tests/frontend: Add AWS GUI test for external etcd and custom CA
  installer/frontend/__tests__/examples/aws-custom-vpc-in.json
  installer/frontend/__tests__/examples/aws-external-etcd-in.json
  installer/frontend/__tests__/examples/aws-in.json
  installer/frontend/ui-tests/output/aws-external-etcd.tfvars
  installer/frontend/ui-tests/pages/certificateAuthorityPage.js
  installer/frontend/ui-tests/pages/clusterInfoPage.js
  installer/frontend/ui-tests/pages/consoleLoginPage.js
  installer/frontend/ui-tests/pages/networkingPage.js
  installer/frontend/ui-tests/pages/nodesPage.js
  installer/frontend/ui-tests/tests/aws.js
Labels: run-gui-tests

#2976 frontend: Get current version info from /tectonic/facts
  installer/assets/frontend/css/styles.css
  installer/frontend/.babelrc
  installer/frontend/components/header.jsx
  installer/frontend/package.json
  installer/frontend/reducer.js
  installer/frontend/server.js
  installer/frontend/tectonic-ga.js
  installer/frontend/utils.js
  installer/frontend/yarn.lock
Labels: run-gui-tests

#2999 Cherry-pick offline changes
  config.tf
  modules/ignition/ca_certs.tf
  modules/ignition/resources/services/k8s-node-bootstrap.service
  platforms/metal/cl/bootkube-controller.yaml.tmpl
  platforms/metal/cl/bootkube-worker.yaml.tmpl
  platforms/metal/cl/custom-ca.yaml.tmpl
  platforms/metal/matchers.tf
  platforms/metal/profiles.tf
Labels: platform/aws, platform/bare-metal, run-smoke-tests

#2998 Cherry-pick OpenStack PRs
  modules/dns/designate/outputs.tf
  modules/openstack/nodes/ignition.tf
  platforms/openstack/neutron/main.tf
Labels: platform/openstack, run-smoke-tests

#3007 frontend: Remove old check for progress files
  installer/frontend/reducer.js
Labels: run-gui-tests

#3006 frontend: Remove unused parameter
  installer/frontend/ui-tests/pages/networkingPage.js
Labels: run-gui-tests

#3008 frontend: Clean up batchSetIn() action
  installer/frontend/actions.js
Labels: run-gui-tests

#3014 modules/aws: enable cluster recovery after cleanup
  modules/aws/master-asg/resources/init-assets.sh
Labels: platform/aws, run-smoke-tests

#3010 Cherry pick PR 2954
  config.tf
  modules/tectonic/resources/manifests/updater/tectonic-monitoring-config.yaml
Labels: platform/aws, platform/azure, platform/bare-metal, run-smoke-tests

#3016 platforms/vmware: Use NodePort for tectonic-lb service
  platforms/vmware/tectonic.tf
Labels: platform/vmware, run-smoke-tests

#2917 tectonic: pull in default network policy (utility), enable ingress controller operator
  config.tf
  modules/bootkube/resources/manifests/02-ingress-namespace.yaml
  modules/tectonic/assets.tf
  modules/tectonic/resources/manifests/cluster-config.yaml
  modules/tectonic/resources/manifests/ingress/README.md
  modules/tectonic/resources/manifests/ingress/cluster-config.yaml
  modules/tectonic/resources/manifests/ingress/namespace.yaml
  modules/tectonic/resources/manifests/ingress/pull.json
  modules/tectonic/resources/manifests/ingress/svc-account.yaml
  modules/tectonic/resources/manifests/rbac/binding-admin.yaml
  modules/tectonic/resources/manifests/updater/app_versions/app-version-tectonic-ingress.yaml
  modules/tectonic/resources/manifests/updater/operators/tectonic-ingress-controller-operator.yaml
  modules/tectonic/resources/tectonic.sh
Labels: platform/aws, platform/azure, platform/bare-metal, run-smoke-tests

#3022 *: bump Tectonic Monitoring to 1.9.4
  config.tf
Labels: platform/aws, run-smoke-tests

#3018 Parameterize Slack integration
  Jenkinsfile
Labels: platform/azure, run-gui-tests, run-smoke-tests

#3026 frontend: Remove some uses of DEFAULT_CLUSTER_CONFIG
  installer/frontend/actions.js
  installer/frontend/cluster-config.js
Labels: run-gui-tests

#3020 frontend: Fix confusing Cluster Name validation error message
  installer/frontend/fields.js
  installer/frontend/ui-tests/pages/clusterInfoPage.js
Labels: run-gui-tests

#3032 *: bump monitoring stack to 1.9.5
  config.tf
Labels: platform/aws, platform/azure, platform/bare-metal, run-smoke-tests

#3019 frontend: Use Redux action creators for all action types
  installer/frontend/__tests__/fields.js
  installer/frontend/__tests__/protocols.js
  installer/frontend/__tests__/reducer.js
  installer/frontend/actions.js
  installer/frontend/app.jsx
  installer/frontend/aws-actions.js
  installer/frontend/components/aws-vpc.jsx
  installer/frontend/components/bm-matchbox.jsx
  installer/frontend/components/bm-nodeforms.jsx
  installer/frontend/components/ui.jsx
  installer/frontend/form.js
  installer/frontend/reducer.js
  installer/frontend/server.js
Labels: run-gui-tests

#3033 frontend: Async fixes and improvements
  installer/frontend/aws-actions.js
  installer/frontend/components/aws-cloud-credentials.jsx
  installer/frontend/components/aws-vpc.jsx
  installer/frontend/form.js
Labels: run-gui-tests

#2983 tests: Make rspec use Tectonic cli on AWS
  Jenkinsfile
  tests/rspec/.rubocop.yml
  tests/rspec/lib/aws_cluster.rb
  tests/rspec/lib/cluster.rb
  tests/rspec/lib/cluster_factory.rb
  tests/rspec/lib/cluster_support.rb
  tests/rspec/lib/config_file.rb
  tests/rspec/lib/shared_examples/build_folder_setup.rb
  tests/rspec/lib/shared_examples/k8s.rb
  tests/rspec/lib/smoke_test.rb
  tests/rspec/lib/test_container.rb
  tests/rspec/lib/tfstate_file.rb
  tests/rspec/spec/aws/basic_spec.rb
  tests/rspec/spec/spec_helper.rb
  tests/smoke/aws/vars/aws.basic.yaml
  tests/smoke/aws/vars/aws.tfvars.json
Labels: platform/aws, platform/azure, run-smoke-tests

#3037 frontend: Remove Matchbox fields from DEFAULT_CLUSTER_CONFIG
  installer/frontend/cluster-config.js
  installer/frontend/components/bm-matchbox.jsx
Labels: run-gui-tests

#3035 frontend: Remove field default check in configActionTypes.SET reducer
  installer/frontend/reducer.js
Labels: run-gui-tests

#3036 tests: update govcloud to use roles and the new aws govcloud account
  Documentation/variables/govcloud.md
  Jenkinsfile
  contrib/govcloud/main.tf
  contrib/govcloud/vars.tf
  examples/terraform.tfvars.govcloud
  platforms/govcloud/main.tf
  platforms/govcloud/variables.tf
  tests/rspec/lib/govcloud_cluster.rb
  tests/rspec/lib/govcloud_vpc.rb
  tests/rspec/spec/govcloud/vpc_internal_spec.rb
Labels: area/ci, area/testing, platform/aws, platform/bare-metal, platform/govcloud, run-smoke-tests

#3044 frontend: Remove Etcd radio "required" validator
  installer/frontend/components/nodes.jsx
Labels: run-gui-tests

#2941 Log file uploader adds Jenkins job & logfile name to metadata
  Jenkinsfile
  tests/jenkins-jobs/scripts/log-analyzer-copy.sh
Labels: platform/aws, run-gui-tests, run-smoke-tests

#3017 Parameterize github repository in Jenkinsfile
  Jenkinsfile
  tests/jenkins-jobs/scripts/report-status-to-github.sh
  tests/jenkins-jobs/tectonic_builder_docker_image.groovy
  tests/jenkins-jobs/tectonic_installer_public_pr_trigger.groovy
  tests/jenkins-jobs/tectonic_smoke_test_docker_image_job.groovy
Labels: platform/aws, platform/azure, platform/bare-metal, run-gui-tests, run-smoke-tests

#3048 installer: revert change that broke bindata
  installer/assets/BUILD.bazel
Labels: platform/aws, run-smoke-tests
